### ISSUE TITLE
Another uncaught permission error

### ISSUE THREAD

**Issue by a223y** [iotaledger/ict#35]
```Feb 26 11:18:06 iota-node iri[6421]:         at com.ictreport.ixi.utils.IctRestCaller.getInfo(IctRestCaller.java:29)
Feb 26 11:18:06 iota-node iri[6421]:         at com.ictreport.ixi.ReportIxiContext.loadIctInfo(ReportIxiContext.java:302)
Feb 26 11:18:06 iota-node iri[6421]:         at com.ictreport.ixi.ReportIxiContext.<init>(ReportIxiContext.java:72)
Feb 26 11:18:06 iota-node iri[6421]:         at org.iota.ict.ixi.ReportIxi.<init>(ReportIxi.java:40)
Feb 26 11:18:06 iota-node iri[6421]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Feb 26 11:18:06 iota-node iri[6421]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:6
Feb 26 11:18:06 iota-node iri[6421]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImp
Feb 26 11:18:06 iota-node iri[6421]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Feb 26 11:18:06 iota-node iri[6421]:         at org.iota.ict.ixi.IxiModuleHolder.createInstance(IxiModuleHolder.java:164)
Feb 26 11:18:06 iota-node iri[6421]:         at org.iota.ict.ixi.IxiModuleHolder.initModule(IxiModuleHolder.java:142)
Feb 26 11:18:06 iota-node iri[6421]:         at org.iota.ict.ixi.IxiModuleHolder.initModulesFromFiles(IxiModuleHolder.java:128)
Feb 26 11:18:06 iota-node iri[6421]:         at org.iota.ict.ixi.IxiModuleHolder.initAllModules(IxiModuleHolder.java:113)
Feb 26 11:18:06 iota-node iri[6421]:         at org.iota.ict.Main.main(Main.java:353)
Feb 26 11:18:06 iota-node iri[6421]: Caused by: java.io.FileNotFoundException: logs/ict.log (Permission denied)
Feb 26 11:18:06 iota-node iri[6421]:         at java.io.FileOutputStream.open0(Native Method)
Feb 26 11:18:06 iota-node iri[6421]:         at java.io.FileOutputStream.open(FileOutputStream.java:270)
Feb 26 11:18:06 iota-node iri[6421]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
Feb 26 11:18:06 iota-node iri[6421]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
Feb 26 11:18:06 iota-node iri[6421]:         at org.apache.logging.log4j.core.appender.FileManager.createOutputStream(FileManager.java:188
Feb 26 11:18:06 iota-node iri[6421]:         at org.apache.logging.log4j.core.appender.OutputStreamManager.getOutputStream(OutputStreamMan
Feb 26 11:18:06 iota-node iri[6421]:         at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStream
Feb 26 11:18:06 iota-node iri[6421]:         ... 43 more
```

**Comment by a223y** [comment]
Suggestion: Format it into ```ERROR: Unable to write a log file ( permission denied )```

**Comment by mikrohash** [comment]
Please report this in the [Report.ixi repository](https://github.com/trifel/report.ixi).
