### ISSUE TITLE
Either methods (A or B) don't work

### ISSUE THREAD

**Issue by slkwd** [iotaledger/ict#5]
The result is always the same:

**/opt/ict $> java -jar ict-0.3-SNAPSHOT.jar**
_WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
	at org.iota.ict.Main.<clinit>(Main.java:25)_

I'm on 
System Version:	**macOS 10.14.2 (18C54)**
Kernel Version:	**Darwin 18.2.0**

Am I miss something?

**Comment by mikrohash** [comment]
Please report back whether this fixes it.

**Comment by slkwd** [comment]
Fixed.
Thanks.
