### ISSUE TITLE
Java Heap Memory error is back

### ISSUE THREAD

**Issue by lambtho12** [iotaledger/ict#67]
For an unknown reason, it seems that the infamous `java.lang.OutOfMemoryError: Java heap space` is back. 

Many people reported it on discord. Usually they run Ict 0.6, along with Report.ixi 0.6 and chat.ixi 1.5 .

**Comment by mikrohash** [comment]
Can you run with `--debug` and report back on the stats provided?

**Comment by mikrohash** [comment]
It would be of great help to know whether this can be reproduced without IXIs.

**Comment by lambtho12** [comment]
Just had the following error this morning. Ict has been running for 4 days with Report, Chat, Tinder and EC.
I will deactivate all IXIs and run Ict with --debug to see what happen next.

It seems that I first had this error
```
Apr 11 02:24:24 DietPi java[18779]: 02:24:24.585 ERROR [org.iota.ictinder.IcTinder/IcTinder]   Unexpected issue occurred during syncing. - java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
Apr 11 02:24:24 DietPi java[18779]:         at org.iota.ict.api.HttpGateway.sendRequest(HttpGateway.java:39)
Apr 11 02:24:24 DietPi java[18779]: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
Apr 11 02:24:24 DietPi java[18779]:         at org.iota.ict.api.HttpGateway.sendRequest(HttpGateway.java:39)
Apr 11 02:24:24 DietPi java[18779]:         at org.iota.ict.api.HttpGateway.sendPostRequest(HttpGateway.java:23)
Apr 11 02:24:24 DietPi java[18779]:         at org.iota.ictinder.IcTinder.sync(IcTinder.java:71)
Apr 11 02:24:24 DietPi java[18779]:         at org.iota.ictinder.IcTinder.run(IcTinder.java:42)
Apr 11 02:24:24 DietPi java[18779]:         at java.lang.Thread.run(Thread.java:748)
Apr 11 02:24:24 DietPi java[18779]: Caused by: java.net.SocketTimeoutException: Read timed out
Apr 11 02:24:24 DietPi java[18779]:         at java.net.SocketInputStream.socketRead0(Native Method)
Apr 11 02:24:24 DietPi java[18779]:         at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
Apr 11 02:24:24 DietPi java[18779]:         at java.net.SocketInputStream.read(SocketInputStream.java:171)
Apr 11 02:24:24 DietPi java[18779]:         at java.net.SocketInputStream.read(SocketInputStream.java:141)
Apr 11 02:24:24 DietPi java[18779]:         at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
Apr 11 02:24:24 DietPi java[18779]:         at sun.security.ssl.InputRecord.read(InputRecord.java:503)
Apr 11 02:24:24 DietPi java[18779]:         at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
Apr 11 02:24:24 DietPi java[18779]:         at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
Apr 11 02:24:24 DietPi java[18779]:         at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
Apr 11 02:24:24 DietPi java[18779]:         at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
Apr 11 02:24:24 DietPi java[18779]:         at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
Apr 11 02:24:24 DietPi java[18779]:         at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:846)
Apr 11 02:24:24 DietPi java[18779]:         at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
Apr 11 02:24:24 DietPi java[18779]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
Apr 11 02:24:24 DietPi java[18779]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
Apr 11 02:24:24 DietPi java[18779]:         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
Apr 11 02:24:24 DietPi java[18779]:         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
Apr 11 02:24:24 DietPi java[18779]:         at org.iota.ict.api.HttpGateway.sendRequest(HttpGateway.java:35)
Apr 11 02:24:24 DietPi java[18779]:         ... 4 more
```

Then it continued working a bit but at each epoch it printed
```
Apr 11 02:45:27 DietPi java[18779]: 02:45:27.793 ERROR [com.ictreport.ixi.api.StatusSender/ReportIxi/IctRestCaller]   Failed to fetch details from Ict REST API (http://localhost:2187/getNeighbors), status code: 500 -
```

then tinder seemd to add and remove neighbor like crazy and eventually
```
Apr 11 07:40:55 DietPi java[18779]: java.lang.OutOfMemoryError: Java heap space
```

**Comment by lambtho12** [comment]
Ok so my Ict was running without any IXIs, and 3 static neighbors
Today I checked the log through ssh and saw that all my neighbors were not responding. I logged in the GUI to check what was happening and then GUI froze.
The logs now indicate:
```
Apr 19 10:33:51 DietPi java[1956]: 10:33:51.460 DEBUG [org.iota.ict.Ict/Ict]   memory: 237MB / 237MB (total/max)
Apr 19 10:34:04 DietPi java[1956]: 10:34:02.325 DEBUG [org.iota.ict.Ict/Ict]   tangle size: 30000 (30000 transaction instances alive)
Apr 19 10:34:24 DietPi java[1956]: java.lang.OutOfMemoryError: Java heap space
Apr 19 10:34:24 DietPi java[1956]:         at java.util.HashMap.resize(HashMap.java:704)
Apr 19 10:34:24 DietPi java[1956]:         at java.util.HashMap.putVal(HashMap.java:629)
Apr 19 10:34:24 DietPi java[1956]:         at java.util.HashMap.put(HashMap.java:612)
Apr 19 10:34:24 DietPi java[1956]:         at org.json.JSONObject.put(JSONObject.java:1611)
Apr 19 10:34:24 DietPi java[1956]:         at org.json.JSONObject.put(JSONObject.java:1571)
Apr 19 10:34:24 DietPi java[1956]:         at org.iota.ict.utils.Stats.toJSON(Stats.java:49)
Apr 19 10:34:24 DietPi java[1956]:         at org.iota.ict.api.JsonIct.neighborStatsToScaledJSON(JsonIct.java:84)
Apr 19 10:34:24 DietPi java[1956]:         at org.iota.ict.api.JsonIct.getNeighbors(JsonIct.java:67)
Apr 19 10:34:24 DietPi java[1956]:         at org.iota.ict.api.RouteGetNeighbors.execute(RouteImpl.java:468)
Apr 19 10:34:24 DietPi java[1956]:         at org.iota.ict.api.RouteImpl.handle(RouteImpl.java:30)
Apr 19 10:34:24 DietPi java[1956]:         at spark.RouteImpl$1.handle(RouteImpl.java:72)
Apr 19 10:34:24 DietPi java[1956]:         at spark.http.matching.Routes.execute(Routes.java:61)
Apr 19 10:34:24 DietPi java[1956]:         at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
Apr 19 10:34:24 DietPi java[1956]:         at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.server.Server.handle(Server.java:530)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
Apr 19 10:34:24 DietPi java[1956]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
Apr 19 10:34:24 DietPi java[1956]:         at java.lang.Thread.run(Thread.java:748)
Apr 19 10:34:24 DietPi java[1956]: Uncaught exeption in thread Thread[org.iota.ict.Ict,5,main]
Apr 19 10:34:24 DietPi java[1956]: java.lang.OutOfMemoryError: Java heap space
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.lookup.StrSubstitutor.getChars(StrSubstitutor.java:1347)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.lookup.StrSubstitutor.substitute(StrSubstitutor.java:905)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.lookup.StrSubstitutor.substitute(StrSubstitutor.java:878)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.lookup.StrSubstitutor.replace(StrSubstitutor.java:433)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.appender.routing.RoutingAppender.append(RoutingAppender.java:224)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2002)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1974)
Apr 19 10:34:24 DietPi java[1956]:         at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:318)
Apr 19 10:34:24 DietPi java[1956]:         at org.iota.ict.Ict.run(Ict.java:86)
Apr 19 10:34:24 DietPi java[1956]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by mikrohash** [comment]
Can you reproduce with tangle capacity = 10,000? I suspect that the 30,000 transactions could be reason for that.

**Comment by lambtho12** [comment]
Ok, will do. Why would 30000 tx cause issues ? It reaches that value quite soon and keep working for a long time at 30k before actually crashing.

**Comment by lambtho12** [comment]
Crashed this morning. All ict.cfg parameters were the default ones. 3 static neighbor, no IXI.
Once again   `Uncaught exeption in thread Thread[org.iota.ict.Ict,5,main]`.

Interestingly I was not even receiving transactions (for some reason all my 3 neighbors were 0|0|0|0|0).


```
Apr 25 07:35:49 DietPi java[5605]: 07:35:49.809 DEBUG [org.iota.ict.Ict/Ict]   memory: 237MB / 237MB (total/max)
Apr 25 07:35:49 DietPi java[5605]: 07:35:49.810 DEBUG [org.iota.ict.Ict/Ict]   tangle size: 10000 (10582 transaction instances alive)
Apr 25 07:35:49 DietPi java[5605]: 07:35:49.811 DEBUG [org.iota.ict.Ict/Node]   forwarding queue size: 0
Apr 25 07:35:49 DietPi java[5605]: 07:35:49.813 DEBUG [org.iota.ict.Ict/TEDwCS]   gossip listeners: 3 / gossip queue size: 0
Apr 25 07:37:00 DietPi java[5605]: Uncaught exeption in thread Thread[org.iota.ict.Ict,5,main]
Apr 25 07:37:00 DietPi java[5605]: java.lang.OutOfMemoryError: Java heap space
```

**Comment by mikrohash** [comment]
Please reopen if it can be replicated with https://github.com/iotaledger/ict/commit/049cb9686245216e7e4e0ef57a7c401320dff918.

**Comment by lambtho12** [comment]
Ok, I will keep the 0.7-SNAPSHOT version you gave me running until the stable release of 0.7, just in case it catches something.
